name: auto_build

on: [push]
  
jobs:
  build_n_deliver:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: docker build push
      run: |
        npm test
        docker build -t mbayu/node-web-app-image .
        docker push mbayu/node-web-app-image
             