name: auto_build

on: [push]
  
jobs:
  build_n_deliver:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: docker build push
      run: |
        echo $(date +%s)
        npm test
        docker build -t mbayu/node-web-app-image .
        docker build . --file Dockerfile --tag mmbayu/node-web-app-image:$(date +%s)
        docker push mmbayu/node-web-app-image:$(date +%s)
             