name: auto_build

on:
  workflow_dispatch:
  
jobs:
  build_n_deliver:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: docker build push
      run: |
        export t=$(date +%s)
        echo $t
        npm test
        docker login
        docker build . --file Dockerfile --tag mbayu/node-web-app-image:$t
        docker images
        docker push mbayu/node-web-app-image:$t
