name: auto_build

on: [push]
  
jobs:
  build:

    runs-on: [self-hosted, linux, x64]

    steps:
    - uses: actions/checkout@v2
    - name: call python http server...to run.as.fast.as.you.can
      run: |
        docker build -t mbayu/node-web-app-image .
        docker push
        echo "hello world"     