name: sbom

on:
  workflow_dispatch:

jobs:
  generate_sbom:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      
      - run: |
          npm install
          
      - uses: CycloneDX/gh-node-module-generatebom@master
        with:
          path: ./.
          output: ./sbom.json
          
      - uses: actions/upload-artifact@v2.3.1
        with:
          name: sbom
          path: sbom.json
